String loginAccountHtml(boolean a, boolean b){
  String html="";
  html+="<!DOCTYPE html>\n";
  html+="  <html>\n";
  html+="  <head>\n";
  html+="    <script src=\"https://kit.fontawesome.com/28e0a3bde9.js\" crossorigin=\"anonymous\"></script>\n";
  html+="    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
  html+="    <title>Login</title>\n";
  html+="    <style>\n";
  html+="      body{\n";
  html+="        font-family: monospace;\n";
  html+="        margin:0px;\n";
  html+="        padding:0px;\n";
  html+="      }\n";
  html+="      .header{\n";
  html+="        background-color:#66a352;\n";
  html+="        font-size:2em;\n";
  html+="        font-weight:600;\n";
  html+="        padding:20px;\n";
  html+="      }\n";
  html+="      .header a{\n";
  html+="        text-decoration:none;\n";
  html+="        color:white;\n";
  html+="      }\n";
  html+="      .login-wrapper{\n";
  html+="        display:block;\n";
  html+="        margin:150px auto;\n";
  html+="        max-width:255px;\n";
  html+="        background-color:#e1e4e6;\n";
  html+="        border-radius:25px;\n";
  html+="        padding-bottom:20px;\n";
  html+="      }\n";
  html+="      .login-heading{\n";
  html+="        font-size: 1.5em;\n";
  html+="        color:white;\n";
  html+="        text-align: center;\n";
  html+="        font-weight:bold;\n";
  if(a==0){
    html+="        background-color:#66a352;\n";
  }
  else if((a==1) && (b==0)){
    html+="        background-color:red;\n";
  }
  html+="        padding: 10px;\n";
  html+="        margin-bottom:40px;\n";
  html+="      }\n";
  html+="      .user-input-box, .pass-input-box{\n";
  html+="        background-color:white;\n";
  html+="        border:2px solid #95a7bf;\n";
  html+="        border-radius:10px;\n";
  html+="        margin:10px auto 10px 10px;\n";
  html+="        height: 20px;\n";
  html+="        width:70%;\n";
  html+="        max-width:200px;\n";
  html+="        padding-left:25px;\n";
  html+="      }\n";
  html+="      .login-button{\n";
  html+="        transition: 0.5s;\n";
  html+="        color:white;\n";
  html+="        font-family:monospace;\n";
  html+="        font-weight:800;\n";
  html+="        border-radius:10px;\n";
  html+="        padding:10px 20px;\n";
  html+="        background-color: orange;\n";
  html+="        margin:10px auto 10px 10px;\n";
  html+="        border:0px\n";
  html+="      }\n";
  html+="      .fa-user, .fa-key{\n";
  html+="        position: absolute;\n";
  html+="        padding:15px;\n";
  html+="      }\n";
  html+="      .user, .password {\n";
  html+="        transition:color 1s;\n";
  html+="        color:#cccac6;\n";
  html+="      }\n";
  html+="      .forget a{\n";
  html+="        text-decoration:none;\n";
  html+="        color:blue;\n";
  html+="      }\n";
  html+="      .forget{\n";
  html+="        text-align:right;\n";
  html+="        margin-right:20px;\n";
  html+="        font-weight:bold;\n";
  html+="      }\n";
  html+="      .user:hover, .password:hover{\n";
  html+="        transition:color 1s;\n";
  html+="        color:#84bcdb;\n";
  html+="      }\n";
  html+="      .login-button:hover{\n";
  html+="        transition: 0.5s;\n";
  html+="        font-size:1.6em;\n";
  html+="        background-color: #74bee8;\n";
  html+="        color:white;\n";
  html+="        font-weight:900;\n";
  html+="      }\n";
  html+="      </style>\n";
  html+="    </head>\n";
  html+="    <body onselectstart=\"return false\">\n";
  html+="      <div class=\"header\">\n";
  html+="        <a href=\"https://www.eccircuit.com/\">Ec IoT</a>\n";
  html+="      </div>\n";
  html+="      <div class=\"login-wrapper\">\n";
  html+="        <div class=\"login-heading\">LOGIN</div>\n";
  html+="        <form action=\"/action_page\" method=\"post\">\n";
  html+="          <div class=\"user\">\n";
  html+="          <i class=\"fas fa-user\"></i>\n";
  html+="          <input class=\"user-input-box\" type=\"text\" name =\"username\" placeholder=\"Username\"/>\n";
  html+="          </div>\n";
  html+="          <div class=\"password\">\n";
  html+="          <i class=\"fas fa-key\"></i>\n";
  if(b==0){
    html+="          <input class=\"pass-input-box\" type=\"password\" name =\"pass\" placeholder=\"Password\"/>\n";
  }
  else if(b==1){
    html+="          <input class=\"pass-input-box\" type=\"password\" name =\"pass\" placeholder=\"Secret Key\"/>\n";
  }
  html+="          </div>\n";
  html+="          <input class=\"login-button\" type=\"submit\" value=\"login\"/>\n";
  html+="          </form>\n";
  if(b==0){
    html+="          <div class=\"forget\">\n";
    html+="          <a href=\"/forget\">forget Password</a>\n";
    html+="        </div>\n";
  }
  html+="        </div>\n";
  html+="      </body>\n";
  html+="  </html>\n";
return html;
}

String settingHtml(){
  String html="";
  html+="<!DOCTYPE html>\n";
  html+="<html>\n";
  html+="<head>\n";
  html+="  <script src=\"https://kit.fontawesome.com/28e0a3bde9.js\" crossorigin=\"anonymous\">\n";
  html+="  </script>\n";
  html+="  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n";
  html+="  <title>Create Account</title>\n";
  html+="  <script>\n";
  html+="    var check = function() {\n";
  html+="      if (document.getElementById('password').value ==\n";
  html+="        document.getElementById('confirm_password').value) {\n";
  html+="        document.getElementById('confirm_password').style.borderColor ='green';\n";
  html+="      } else {\n";
  html+="        document.getElementById('confirm_password').style.borderColor ='red';\n";
  html+="      }\n";
  html+="    }\n";
  html+="    function toggle_input(i) {\n";
  html+="    var input = document.getElementsByTagName('input');\n";
  html+="      input[i].disabled = !input[i].disabled;\n";
  html+="      if(input[i].disabled){\n";
  html+="        console.log(input[i].enabled);\n";
  html+="        input[i].style.background =\"#bbbfbf\";\n";
  html+="      }\n";
  html+="      else{\n";
  html+="        input[i].style.background=\"white\";\n";
  html+="      }\n";
  html+="    }\n";
  html+="    function change_mode(){\n";
  html+="      var tag = document.getElementById(\"mode\");\n";
  html+="      if(tag.style.color==\"white\"){\n";
  html+="        tag.style.color=\"black\";\n";
  html+="        tag.style.background=\"#6db3b3\";\n";
  html+="        tag.innerHTML=\"Light\";\n";
  html+="        document.getElementById('colormode').value='Light';\n";
  html+="      }\n";
  html+="      else{\n";
  html+="        tag.style.color=\"white\";\n";
  html+="        tag.style.background=\"#0f3460\";\n";
  html+="        tag.innerHTML=\"Dark\";\n";
  html+="        document.getElementById('colormode').value='Dark';\n";
  html+="      }\n";
  html+="    }\n";
  html+="    </script>\n";
  html+="  <style>\n";
  html+="    body{\n";
  html+="      margin:0px;\n";
  html+="      padding:0px;\n";
  html+="      font-family:monospace;\n";
  html+="    }\n";
  html+="    .wrapper{\n";
  html+="      text-align:center;\n";
  html+="      display:block;\n";
  html+="      margin:100px auto;\n";
  html+="      padding-bottom:40px;\n";
  html+="      max-width:550px;\n";
  html+="      width:70%;\n";
  html+="      border-radius:20px;\n";
  html+="      background-color:#e1e4e6;\n";
  html+="    }\n";
  html+="    .ca-heading{\n";
  html+="      font-size: 1.5em;\n";
  html+="      color:white;\n";
  html+="      text-align: center;\n";
  html+="      font-weight:bold;\n";
  html+="      background-color:#66a352;\n";
  html+="      padding: 10px;\n";
  html+="      margin-bottom:40px;\n";
  html+="    }\n";
  html+="    .inputbox{\n";
  html+="      background-color:#bbbfbf;\n";
  html+="      border:2px solid #95a7bf;\n";
  html+="      border-radius:10px;\n";
  html+="      margin:10px auto 10px 10px;\n";
  html+="      height: 20px;\n";
  html+="      width:50%;\n";
  html+="      max-width:200px;\n";
  html+="      padding-left:25px;\n";
  html+="    }\n";
  html+="    .confirm-button{\n";
  html+="      transition: 0.5s;\n";
  html+="      color:white;\n";
  html+="      font-family:monospace;\n";
  html+="      font-weight:800;\n";
  html+="      border-radius:10px;\n";
  html+="      padding:10px 20px;\n";
  html+="      background-color: orange;\n";
  html+="      margin:10px auto 10px 0px;\n";
  html+="      border:0px\n";
  html+="    }\n";
  html+="    .confirm-button:hover{\n";
  html+="      transition: 0.5s;\n";
  html+="      font-size:1.6em;\n";
  html+="      background-color: #74bee8;\n";
  html+="      color:white;\n";
  html+="      font-weight:900;\n";
  html+="    }\n";
  html+="    .fas{\n";
  html+="      position: absolute;\n";
  html+="      padding:15px;\n";
  html+="    }\n";
  html+="    .hov{\n";
  html+="      transition:color 0.5s;\n";
  html+="      color:#cccac6;\n";
  html+="    }\n";
  html+="    .hov:hover{\n";
  html+="      transition:color 0.5s;\n";
  html+="      color:#84bcdb;\n";
  html+="    }\n";
  html+="    .fa-edit{\n";
  html+="      color:blue;\n";
  html+="    }\n";
  html+="    .fa-edit:hover{\n";
  html+="      transition: 0.5s;\n";
  html+="      background-color: #74bee8;\n";
  html+="      border-radius:20px;\n";
  html+="      color:white;\n";
  html+="      font-weight:900;\n";
  html+="    }\n";
  html+="    #mode{\n";
  html+="      font-size:1.3em;\n";
  html+="      font-family:arial;\n";
  html+="      font-waight:500;\n";
  html+="      width:30%;\n";
  html+="      color:black;\n";
  html+="      padding:10px 20px;\n";
  html+="      margin:10px auto;\n";
  html+="      background-color:#6db3b3;\n";
  html+="      border-radius:20px;\n";
  html+="    }\n";
  html+="    </style>\n";
  html+="    </head>\n";
  html+="    <body>\n";
  html+="      <div class=\"wrapper\">\n";
  html+="        <div class=\"ca-heading\">Setting</div>\n";
  html+="        <form action=\"/action_page\" method=\"post\">\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-signature\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"text\" name=\"c_name\" Placeholder=\"Name\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('0')\"></i>\n";
  html+="            </div>\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-user\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"text\" name=\"c_username\" Placeholder=\"Username\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('1')\"></i>\n";
  html+="            </div>\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-key\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"password\" id=\"password\" name=\"c_password\" Placeholder=\"Password\" onkeyup=\"check()\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('2')\"></i>\n";
  html+="            </div>\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-key\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"password\" id=\"confirm_password\" Placeholder=\"Confirm Password\" onkeyup=\"check()\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('3')\"></i>\n";
  html+="            </div>\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-wifi\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"text\" name=\"c_ssid\" Placeholder=\"WiFi SSID\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('4')\"></i>\n";
  html+="            </div>\n";
  html+="          <div class=\"hov\">\n";
  html+="            <i class=\"fas fa-lock\"></i>\n";
  html+="            <input class=\"inputbox\" type=\"text\" name=\"c_wifi_password\" Placeholder=\"WiFi Password\" disabled/>\n";
  html+="            <i class=\"fas fa-edit\" onclick=\"toggle_input('5')\"></i>\n";
  html+="          </div>\n";
  html+="          <input id=\"colormode\" name=\"mode\" type=\"hidden\" value=\"Light\"/>\n";
  html+="          <div id=\"mode\" onclick=\"change_mode()\">Light</div>\n";
  html+="          <div>\n";
  html+="            <input class=\"confirm-button\" type=\"submit\" value=\"Confirm\"/>\n";
  html+="            </div>\n";
  html+="          </form>\n";
  html+="        </div>\n";
  html+="      </body>\n";
  html+="      </html>\n";
  return html;
}
